steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
    '--tag', 'us.gcr.io/$PROJECT_ID/${_IMAGE}:${_VERSION}',
    '--tag', 'us.gcr.io/$PROJECT_ID/${_IMAGE}:latest',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/${_IMAGE}:latest',
    '.' ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/fides-server', 'fides-server=us.gcr.io/$PROJECT_ID/${_IMAGE}:${_VERSION}']
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-east4-a
      - CLOUDSDK_CONTAINER_CLUSTER=fides-server-cluster
timeout: 1200s
substitutions:
  _IMAGE: fides-server
  _VERSION: latest
images:
  - 'us.gcr.io/$PROJECT_ID/${_IMAGE}:${_VERSION}'
  - 'us.gcr.io/$PROJECT_ID/${_IMAGE}:latest'