kind: Service
apiVersion: v1
metadata:
  name: fides-server-service
spec:
  selector:
    app: fides-prod
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 35.245.17.134 # <- Update IP Here
